version: '3'

services:
  app:
    build: .
    container_name: wechat-article-downloader
    ports:
      - "29212:8000"
    volumes:
      - ./data/html:/artlist/html
      - ./data/json:/artlist/json
      - ./data/logs:/artlist/logs
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB=wechat_articles
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongo-data: 